name: ElissaBallard
favicon: null
layout_spectrum: 0
typography_spectrum: 0.08210154250264168
description: Awakened Practices for Every-Day Living
navigation:
  - name: Mindfulness in Education
    id: e0efe126-b644-4696-848b-08d241610f2d
    type: content
  - name: Yoga
    id: 718b0051-161e-4f45-abeb-f0ba1ff3a77f
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Yoga & Mindfulness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BE7F3C'
    - '#D5D9DC'
    - '#47351B'
    - '#AE5D11'
    - '#C0A686'
  brandStrength: 0.3235192862339318
  lightness: 0.8433584
  saturation: 0.4874687
  rhythmicContrast: 0.7926065
purpose: []
